### ISSUE TITLE
reactor.version -> reactor-core.version

### ISSUE THREAD

**Issue by sdeleuze** [bclozel/spring-boot-web-reactive#13]
Since Reactor projects have their own lifecycle and there is not a single Reactor version anymore, that would be maybe less confusing to use a name like `reactor-core.version` rather than `reactor.version`.

**Comment by snicoll** [comment]
We can't do that. `reactor.version` is the standard property in Spring Boot. I have to override that.

I've asked proactively to you guys what we should do in Spring Boot and I even created an issue in our own tracker. It was decided the BOM is the move and so the current `reactor.version` will be reused, see https://github.com/spring-projects/spring-boot/issues/6409
