### ISSUE TITLE
starter does not work with the latest Framework snapshot

### ISSUE THREAD

**Issue by snicoll** [bclozel/spring-boot-web-reactive#14]
See [this issue](https://jira.spring.io/browse/SPR-14576) and [this commit](https://github.com/spring-projects/spring-framework/commit/dfef4e09daf17c3e37226199309423db790b2ce7)

Thanks @violetagg !

**Comment by tzachis** [comment]
Thanks for the quick fix!

**Comment by bclozel** [comment]
Thanks a lot @snicoll
