### ISSUE TITLE
Sample-web-reactive hangs on every other request.

### ISSUE THREAD

**Issue by PedroAlvarado** [bclozel/spring-boot-web-reactive#21]
Using the reactor-netty profile on the sample-web-reactive app causes every other request to hang. I've been able to reproduce this issue in master of this project and on my own reactor-netty-based test applications. This doesn't happen when using any of the other profiles including the rxnetty profile.

Steps to reproduce:

1. Enable the reactor-netty profile

`<id>reactor-netty</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>`
2. Compile and deploy the sample-web-reactive
3. Hit localhost:8080 and notice a successful response.     
4. Hit localhost:8080 and notice the pending request effectively hanging.      

@bclozel Let me know if there is any other information you need me to provide to further diagnose this issue. From a quick inspection, this issue is likely to be somewhere deep in reactor-netty.

**Comment by danielfernandez** [comment]
This seems to be the same as reactor/reactor-ipc#20

**Comment by PedroAlvarado** [comment]
@danielfernandez Indeed it is. I'm working around this by using RxNetty instead. Meaning this is likely an issue in reactor-netty. Let's leave this  issue open to make sure that the fix rolls up to this repo.

**Comment by sdeleuze** [comment]
Same issue on https://github.com/sdeleuze/spring-reactive-playground

**Comment by sdeleuze** [comment]
The related bug has been fixed in Reactor Netty 0.5.2.RELEASE (has just been deployed to Maven Central).
