### ISSUE TITLE
Documentation for External Service Calls:

### ISSUE THREAD

**Issue by nitin02** [bclozel/spring-boot-web-reactive#34]
I'm trying to implement the "External Service Calls" as given in this link.

https://spring.io/blog/2016/06/07/notes-on-reactive-programming-part-i-the-reactive-landscape

Please provide an example/documentation on how to implement this.

General Idea:

Assume, a case where an input HTTP request requires multiple external service calls to happen non-blocking and asynchronous. The HTTP response is ideally an aggregation of response from the external service calls.

**Comment by bclozel** [comment]
I'm currently working on an example application for a talk.

Depending on how you want to deal with things those external service calls can happen in parallel or in sequence. That's where [Reactor operators](http://projectreactor.io/core/docs/api/) really shine.

Here's a naive example with parallel HTTP requests, with results being "zipped" into a single object.

```java
WebClient webClient = WebClient.create(new ReactorClientHttpConnector());

ClientRequest<User> userRequest = ClientRequest
    .GET("http://example.spring.io/users/{name}", "nitin02")
    .accept(MediaType.APPLICATION_JSON).build();

ClientRequest<Account> accountRequest = ClientRequest
    .GET("http://example.com/accounts/{id}", 42L)
    .accept(MediaType.APPLICATION_JSON).build();

Mono<User> user = this.webClient
    .exchange(userRequest)
    .then(response -> response.body(toMono(User.class)));
Mono<Account> account = this.webClient
    .exchange(accountRequest)
    .then(response -> response.body(toMono(Account.class)));

Mono<UserAccount> userAccount = Mono.zip(values -> new UserAccount(values[0], values[1]), user, account);
```

If you want to learn more about reactor, you can check [this hands on which explains reactor operator with concrete examples](https://github.com/reactor/lite-rx-api-hands-on/).
