### ISSUE TITLE
Formatters/Converters not being automatically registered

### ISSUE THREAD

**Issue by danielfernandez** [bclozel/spring-boot-web-reactive#55]
The auto-configuration mechanism for Spring Web Reactive applications doesn't seem to be auto-registering `@Bean` objects of type `Formatter` and `Converter`/`GenericConverter` contrary to what `WebMvcAutoConfiguration` does.

I'm creating a Spring Web Reactive-enabled version of the Thymeleaf STSM example application, using Spring Boot `2.0.0.BUILD-SNAPSHOT` and the `spring-boot-web-reactive` starter, and [these beans](https://github.com/thymeleaf/thymeleafexamples-stsm-reactive/blob/SPRING_BOOT_WEB_REACTIVE_55/src/main/java/thymeleafexamples/stsm/StsmReactiveWebConfig.java):

```java
    @Bean
    public VarietyFormatter varietyFormatter() {
        return new VarietyFormatter();
    }

    @Bean
    public DateFormatter dateFormatter() {
        return new DateFormatter();
    }
```

Are apparently not being auto-registered.

**Comment by danielfernandez** [comment]
I've just created the `SPRING_BOOT_WEB_REACTIVE_55` tag at the [`thymeleaf/thymeleafexamples-stsm-reactive`](https://github.com/thymeleaf/thymeleafexamples-stsm-reactive/tree/SPRING_BOOT_WEB_REACTIVE_55) repository so that you can use it as an example repo for this issue.

Just start the app with `mvn -U clean compile spring-boot:run` and access `http://localhost:8080`. You'll notice a text input field with a value such as `Fri Dec 09 18:33:01 CET 2016`, which means the  formatters are not being registered (it should be something like `09/12/2016`.

**Comment by danielfernandez** [comment]
Added pull request for this at #56

**Comment by danielfernandez** [comment]
I'm in the process of creating some new web application examples integrating Thymeleaf and Spring Web Reactive, and the lack of `Formatter` auto-registry basically keeps me from being able to use the existing auto-configuration mechanism for the rest of the Spring Web Reactive infrastructure... hey, not killing my life, but certainly uncomfortable...

So I'm really sorry to insist but, is there a possibility this is added soon (via the PR or any other implementation)? please please please 😄

**Comment by bclozel** [comment]
Yeah sorry, I'll get right to it

**Comment by bclozel** [comment]
It was indeed very similar to the current arrangement in Boot for MVC - Thanks for the PR!
