### ISSUE TITLE
Support customized Jackson configuration

### ISSUE THREAD

**Issue by sdeleuze** [bclozel/spring-boot-web-reactive#59]
Like with Spring Boot + Spring MVC, Spring Boot Web Reactive should support customizing Jackson `ObjectMapper` by detecting `ObjectMapper`, `Jackson2ObjectMapperBuilder` and `Module` beans declared in `@Configuration` classes and use them to customize `HttpMessageWriter`s and `HttpMessageReader`s in `ReactiveWebAutoConfiguration`.

**Comment by sdeleuze** [comment]
Another related open question is how the `ObjectMapper` used in `WebClient` could be easily customized.

**Comment by lgbanuelos** [comment]
Is there a way to configure Spring Boot Web Reactive's `ObjectMapper` to customize the serialization of Java date/time classes? I understand you are planning to implement something similar to what the non-reactive Spring Boot supports in that respect but, is there a workaround that I could use in the meantime? All the examples I have found on the web so far apply only to non-reactive Spring Boot applications.

**Comment by dbacinski** [comment]
Any ETA on this? 

Without it I am not able to expose REST api with date attribute. 

By default Jackson is formatting dates to arrays like this: `"creationDate":[2017,5,11,11,39,32,90000000]` which is pretty useless.

**Comment by bclozel** [comment]
This repository is now deprecated.
You can find the new issue here: spring-projects/spring-boot#9166
