### ISSUE TITLE
Add WebSocket support

### ISSUE THREAD

**Issue by sdeleuze** [bclozel/spring-boot-web-reactive#60]
Example of configuration in [AbstractWebSocketIntegrationTests](https://github.com/spring-projects/spring-framework/blob/master/spring-web-reactive/src/test/java/org/springframework/web/reactive/socket/AbstractWebSocketIntegrationTests.java)

Pay attention to TomcatServer that requires an extra `WsContextListener.class` parameter.

Would be nice to manage version of WebSocket dependencies like the one for Tomcat or Undertow.

**Comment by bclozel** [comment]
See spring-projects/spring-boot#8629
