### ISSUE TITLE
Enable Reactive web server via dedicated @EnableXxx annotation

### ISSUE THREAD

**Issue by sdeleuze** [bclozel/spring-boot-web-reactive#65]
Reactor Netty and RxNetty provide client + server with a single dependency, and even in Spring Framework 5.0 both functionalities are provided in the very same dependency.

So in order to avoid creating a server when you just use `WebClient` for example, I would be for enabled Reactive web server with a dedicated `@EnableXxx` annotation.

**Comment by sdeleuze** [comment]
See related https://github.com/spring-projects/spring-boot/issues/8017 issue.

**Comment by bclozel** [comment]
Indeed, this duplicates the Boot issue. Closing.
