### ISSUE TITLE
NoSuchBeanDefinitionException: ReactiveWebServerFactory

### ISSUE THREAD

**Issue by MarianneAbdelmalek** [bclozel/spring-boot-web-reactive#74]
I was using spring boot and spring-web-reactive for a while now, with the following versions: 
	<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-web-reactive</artifactId>
			<version>5.0.0.M4</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot</artifactId>
                        <version>2.0.0.BUILD-SNAPSHOT</version>
		</dependency>

Three days ago, I found that my app throws a runtime exception:

NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.boot.web.reactive.server.ReactiveWebServerFactory' available.

**Comment by snicoll** [comment]
@MarianneAbdelmalek this starer is deprecated for quite a while now as all features have been merged to Spring Boot (see the README of this project). 

I'd advise you to use the official starter (`spring-boot-starter-webflux`). If you're still having issues integrating it in your app, join us on Gitter or ask on Stackoverflow. Thanks!
